package com.example.sehirtanitmakonya42;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.GridView;

import java.util.ArrayList;

public class MainActivityKonya extends AppCompatActivity {
    GridView KonyaEserler;
    ArrayList<Eser> Eserler=new ArrayList<>();
    KonyaAdaptorAlihan BaglaAdaptor;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        KonyaEserler=(GridView)findViewById(R.id.esr_grdv);
        Eserler.add(new Eser(R.drawable.catalhoyuk,"Çatalhöyük Neolitik Kenti","1958","Konya ilinin Çumra ilçesinde yer alan Çatalhöyük, 1958 tarihinde keşfedilmiştir. Çeşitli aralıklarla yapılan bilimsel kazılar günümüzde de kapsamlı olarak devam etmektedir.Olağan dışı sanatıyla hayranlık uyandıran Neolitik Kent Çatalhöyük’te ilk buluntular MÖ 7400 yıllarına tarihlenmektedir. Kent, medeniyetin ve ziraatin temellerini anlamamızda uluslararası anahtar olarak tanımlanmaktadır. Çatalhöyük’ün Neolitik yerleşim tarzı ve kent planının eşitlik ideallerini yansıttığına inanılmaktadır. "));
        Eserler.add(new Eser(R.drawable.mevlana,"Mevlâna Türbesi Müzesi","1926","Sultanü’l ulema 12 ocak 1231 yılında vefat edince bugünkü yerine defnedilmiştir.bu defin gül bahçesinde yapılan ilk definedir Sultan’ül ulema’nın ölümünden sonra kendisini sevenler Mevlana’ya müracaat ederek babasının mezarının üzerine Nil türbe yaptırmak istediklerini söylemişlerse de Mevlana ‘ Gök kubbeden daha iyi türbe mi olur? Diyerek bu isteği reddetmiştir.Ancak kendisi 7 aralık 1273 yılında vefat edince Mevlana’nın oğlu sultan veled Mevlana’nın mezarının üstünde türbe yaptırmak isteyenlerin isteklerini kabul etmiştir. ‘’kubbe-i hadra’ yeşil türbe denilen türbe dört fil ayağı( kalın sütun) üzerine 130.000 Selçuki dirhemine Mimar Tebrizli Bedreddin’e yaptırılmıştır."));
        Eserler.add(new Eser(R.drawable.sille,"Sille Köyü","MS 327","Bu eski Rum köyü zengin tarihiyle Konya'nın keşfedilmesi gereken önemli noktalardan biridir.Sille Köyü'nün ismini Yunan mitolojisinde Silene kelimesinden geldiği kabul edilmektedir.Konya'nın eski bir yerleşim alanı olan Sille, Selçuklu ilçesine yaklaşık 8 kilometre uzaklıkta bulunmakta. Yapılan arkeolojik araştırmalarda bu yerleşim alanının en az 6000 yıllık olduğu ortaya çıkarılmıştır. Köy boyunca Roma'ya ait birçok kalıntı göze çarpar. Aynı zamanda Bizans, Kudüs ve Roma yolu üzerinde bulunduğu için önemli bir dini merkez olarak kabul görmüştür Sille Köyü. Bu durum dünyanın en eski ve en büyük manastırları arasındaki Hagios Khariton Manastırı'nın (Ak Manastır)bu köyde bulunmasını sağlamıştır. Manastır, köydeki en önemli kalıntıların başında geliyor.Konya Sille Köyü, Selçuklu döneminde de önemini yitirmemiştir. Bunun sebebi o dönemlerde İpek Yolu ve Baharat Yolu üzerinde olmasıdır.Konya'nın en güzel bölgelerinden biri olan Sille Köyü'nü muhakkak keşfetmelisiniz. Köye girdiğiniz an farklı bir zaman dilimine geçtiğinizi hissedecek, bu hissi köyden çıkana kadar yaşayacaksınız."));
        Eserler.add(new Eser(R.drawable.esrefoglu,"Eşrefoğlu Cami","1296-1299","Selçuklu tipi ahşap sütunlu camiler, Osmanlı camilerinden daha bir cezbedici özelliğe sahiptir.Eşrefoğlu Camii, Selçuklu tipi camilerin bir örneğidir ve Anadolu'daki ahşap direkli camilerin en büyüğü ve orijinali durumundadır.Konya'nın Beyşehir ilçesinde bulunmakla birlikte, 1296-1299 yılları arasında yapılmıştır. Eşrefoğlu Süleyman Bey'in isteği üzerine yapılan cami, görkemli bir mihraba sahiptir. Bu mihrap, 6 metre yüksekliğinde olup, çini mozaikler ile kaplıdır. Bir taç kapısının yanı sıra minberi tamamı ile ceviz ağacından yapılmıştır. Eşrefoğlu Camii, Selçuklu Ulu Camilerinde görülen tüm özellikler de taşımaktadır. Ahşap bir özelliği olan bu cami, Kastamonu'da bulunan Mahmut Bey Camii kadar zarif ama iddialıdır."));
        Eserler.add(new Eser(R.drawable.inceminaremedrese,"İnce Minareli Medrese","1956","Bir Selçuklu yapıtı olan İnce Minareli Medrese, Konya'da turistlerin en çok ziyaret ettiği yerlerden biridir.Selçuklu mimarisin örneklerinden olan medrese Selçuklu ilçesinde bulunmakla birlikte, ll. İzzettin Keykavus döneminde yaptırılmıştır. Selçuklu mimarisinde pek kullanılmayan taç kapı bu medresede kullanılmıştır ve medrese tek eyvanlıdır. Harika bir taş işçiliğine sahip olmakla birlikte; 19. yüzyıla kadar kullanılmıştır. Zaman geçtikçe onarım gören medrese 1956 yılında Taş Ahşap Eserler Müzesi olarak hizmete girmiştir.İnce Minareli Medrese'yi Konya gezinizde ziyaret edebilirsiniz."));
        Eserler.add(new Eser(R.drawable.selcuklukosk,"Selçuklu Köşkü","1156-1192","Konya'nın tarihi dokusunu gözler önüne seren Selçuklu Köşkü, II. Sultan Kılıç Arslan döneminde yapılmıştır. Şehir merkezinde ve “Alâeddin Tepesi” diye bilinen höyüğün kuzey eteğindedir; hâlihazırda betonarme şemsiye altında korunmaya çalışılan kârgîr bir yapıdır. Höyüğün üzerindeki görkemli Selçuklu Sarayı’na âit ve bir burç üzerine “belvedere” olarak inşa edildiği anlaşılan köşkten geriye, beden duvarlarının bir bölümü ile üst kat çıkmasını taşıyan tuğla örgülü mukarnaslı iki konsol parçası kalabilmiştir; doğu cephesinde, sıva üzerine kırmızı ve sarı renkli boyalarla yapılmış tuğla taklidi desenlerden oluşan bir duvar resminin kalıntıları dikkati çeker."));
        Eserler.add(new Eser(R.drawable.tinaztepe,"Tınaztepe Mağarası","1968"," Mağaranın uzunluğu 22 km'dir ve bu özelliği onu ülkemizin en büyük mağarası olma unvanını getirmiştir. Mağaranın uzunluğu 22 km'dir ve bu özelliği onu ülkemizin en büyük mağarası olma unvanını getirmiştir. Ziyarete açık olan bölümün uzunluğu 1580 m'dir.Mağara ilk olarak 1968 yılında bir Fransız bilim adamı olan Michel Bakalowichz tarafından keşfedilmiştir.Sonundaki 30 m'lik inişi sayılmaz ise Tınaztepe Mağarası'nın tamamen yatak özelliğe sahip bir mağara olduğu söylenebilmektedir. Ayrıca yapılan araştırmalar yapının 230 milyon yıl içerisinde oluştuğunu göstermektedir. Gerek ulaşım kolaylığı gerek ilgi çekici yapısal özellikleriyle mağara yalnızca ülkemizden değil dünyanın dört bir yanından ziyaretçi ağırlamaya devam etmektedir."));
        Eserler.add(new Eser(R.drawable.beysehirgol,"Beyşehir Gölü","---","Konya'nın Beyşehir ilçesinde bulunan Beyşehir Gölü, Türkiye'nin ikinci büyük gölü olma özelliğine sahiptir. Gölün üzerinde irili ufaklı 33 tane ada vardır. Tabanı neojen göl tortularıyla dolu olup; içinde sazan, aynalı ve levrek gibi balık türlerini yaşatmaktadır. Ayrıca Beyşehir Gölü, halk arasında “'uluarık”' olarak adlandırılan Suğla Gölü'ne akmaktadır.Çevresinde barındırdığı Milli Park, Beyşehir'i zenginleştirmiş; meşe, selvi, karaçam ve göknar ağaçlarıyla gölün etrafını süslemiştir. Özellikle mayıs ve ekim aylarında ziyaretçi yoğunluğuna uğramaktadır. Bedeninizi ve ruhunuzu dinlendireceğiniz Beyşehir Gölü'ne günübirlik gidebileceğiniz gibi birkaç gün kalıp kamp yapma olanağı da bulabilirsiniz. Üstelik gün batımını görebileceğiniz en harika yerlerden biridir. Çünkü Beyşehir Gölü, güneşin batışı sırasında renk ve süresi yönünden dünyada önemli yerler arasındadır."));
        Eserler.add(new Eser(R.drawable.selimiyecami,"Konya Selimiye Camisi","1567","Birçok şehzadenin sancağa çıktığı bu şehir, o dönemlerde inşa edilen yapıların bazılarını günümüze kadar ulaştırmayı başarmıştır.Kesme taş kullanılmak sureti ile yapılan camiinin, kuzey kısmında, yuvarlak biçimli altı adet sütunlu ve yedi adet kubbeli bir son cemaat yeri yer almaktadır. Bahsedilen sütunlar birbirlerine, beyaz ve kırmızı taştan yapılmış olan kemerler ile bağlanmıştır. İbadet edilen alana üç kapıdan giriş yapılmaktadır. Bu üç kapıdan ana giriş kapısı mukarnas dolgulu ve mermerden imal edilmiştir. Aynı zamanda bu giriş kapısı üzerinde, tarihi belli olmayan bir kitabe de yer almaktadır.Sağ tarafta yer alan kapıda ise, camide bulunan mümin sudaki balık gibidir ondan zevk alır şeklinde bir yazı bulunmaktadır. Sol taraftaki kapıda ise, camide bulunan münafık kafeste bunalan kuş gibidir anlamında bir yazı yer almaktadır. İbadet alanları, iki adet kalın paye üzerine oturtulmuş vaziyette ve oldukça yüksek merkezi bir kubbe ile örtülü haldedir. Bahse konu kubbe mihrap önünde yarım bir kubbe ile desteklenmekte, yanlarda ise, üç küçük kubbe ile desteklenmektedir."));
        Eserler.add(new Eser(R.drawable.eflatunpinari,"Eflatun Pınarı","1275-1285","Hititler döneminde yapılmış kutsal bir su anıtı olan Eflatun Pınarı, Konya'nın Beyşehir ilçesine 22 km mesafede yer alıyor.Göğü taşıyan ve yerle gök arasında ilişki kuran tanrıların tasvir edildiği Eflatun Pınarı, hafif dalgalı bir yerde kalkerden ve yassı bir tepenin eteğinde yer alan yaklaşık 100 metrelik bir bölümden kaynıyor.Eflatun Pınarı, görüntüsü itibariyle Konya Ereğli'de bulunan meşhur İvriz Kabartması'nı andırıyor. Kuzey tarafından yüzünü pınara doğru çevirmiş görkemli bir abide yer alıyor. Bu abide 7 metre eninde ve yüksekliğinde olup, 14 muazzam taştan yapılmış. Eski Anadolu stilinde olan Eflatun Pınarı'nın batı kısmında, yerden bir kaynak suyu fışkırıyor ve bu su pınarın önündeki küçük gölün oluşumunu sağlıyor."));
        Eserler.add(new Eser(R.drawable.sahipata,"Sahipata Külliyesi","1259-1279","Selçuklu mimarisinin en güzel örneklerinden biri olan Sahipata Külliyesi yerli ve yabancı turistlere tarihi izlerini göstermeye devam ediyor. Larende Caddesi üzerinde bulunan külliye, Anadolu Selçuklu veziri Sahip Ata Fahrettin Ali tarafından yaptırılmıştır. Külliye; hankah, hamam, türbe ve camiden oluşmakta. 1259-1279 yılları arasında inşa edilmiş olup mimarı Abdullah bin Kölük'tür.Sahipata Külliyesi'nin camisi günümüze kadar gelebilmiş ağaç direkli ibadet mekanlarından biridir. Caminin özellikle taç kapısı ağaç işçiliğinin ne kadar kusursuz işlendiğinin göstergesidir.Sahipata Külliyesi Konya gezisine kesinlikle dahil edilmesi gereken önemli bir tarihi eserdir . Her parçasıyla…"));

        BaglaAdaptor=new KonyaAdaptorAlihan(this,Eserler);
        KonyaEserler.setAdapter(BaglaAdaptor);
        KonyaEserler.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Eser Eser = Eserler.get(position);
                Intent git = new Intent(MainActivityKonya.this, DetayAktiviteAlihan.class);
                git.putExtra("eser", Eser);
                startActivity(git); }
        });
    }
}


